### ISSUE TITLE
[BUG] The top title bar is covered by browser bookmark bar

### ISSUE THREAD

**Issue by kitewu** [X-lab2017/open-galaxy#28]
On the dashboard page, the top title bar is covered by browser bookmark, as shown below:

With chrome bookmark bar:
![with bookmark bar](https://user-images.githubusercontent.com/16188599/147328872-71958aa3-c6e8-46ec-9339-2c119be6be58.png)

Without chrome bookmark bar:
![without bookmark bar](https://user-images.githubusercontent.com/16188599/147328572-fd4b6000-177c-47f5-afec-afcf8ecb93e2.png)

Chrome version: 96.0.4664.110 (x86_64)
System version: MacOS 12.1, 16-inch

**Comment by tyn1998** [comment]
Thank you for your report. It is a known issue #29 that we will fix later. 

Currently we use "px" as CSS unit and this unit works perfect under resolution of 1920*1080. However, MacOS and Windows will autimatically enlarge pixels in high resolution monitors, which leads to this problem.

There is a trick. You can zoom in the page to get a "just OK" layout.

We will fix this ASAP.

**Comment by kitewu** [comment]
> Thank you for your report. It is a known issue #29 that we will fix later.
> 
> Currently we use "px" as CSS unit and this unit works perfect under resolution of 1920*1080. However, MacOS and Windows will autimatically enlarge pixels in high resolution monitors, which leads to this problem.
> 
> There is a trick. You can zoom in the page to get a "just OK" layout.
> 
> We will fix this ASAP.

Cool

**Comment by tyn1998** [comment]
SODA components were removed from the codebase, so this issue will be closed :)
