### ISSUE TITLE
[CI/CD] We need a GitHub action to run CI

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/open-galaxy#4]
As this project is a website so we may need a GitHub action to run CI and put the compile files onto OSS in order to review.

We may need to determine what the dependencies we need to compile the project.

**Comment by frank-zsy** [comment]
@tyn1998 Can you give us a list of dependencies we need to install separately rather than `npm install` or `yarn install`?

**Comment by tyn1998** [comment]
> @tyn1998 Can you give us a list of dependencies we need to install separately rather than `npm install` or `yarn install`?

My case:
- CPU: Apple M1 Pro
- OS: MacOS Moterey
- yarn: v1.22.17
- node: 17.0.1

When I fisrt ran `yarn install`, I was told yarn is "Buiding fresh packages". It seemed that some packages had to be built from scratch. Unfortunately, some core components for building the packages were not in my environment, so I `brew install` them one by one according to yarn's suggestion.

These core components are:
- pkg-config
- pixman
- cairo
- pango

After `brew` install them, I succeeded to finish the `yarn install` process.

**Comment by frank-zsy** [comment]
OK, I will review your PRs after CI get ready.
